product_items_loc = "img.position-absolute"
price_slider_wrapper_loc = ".multirange-wrapper"
first_legs_checkbox_loc = "xpath=(//b[text()='Legs']/following::input[@name='attrib'])[1]"
categories_dropdown_loc = "#top_menu a.nav-link.dropdown-toggle.active"
items_cart_icons = ".fa-shopping-cart"
add_to_card_dialog_title = ".modal-title"
sort_dropdown_loc = ".o_sortby_dropdown .dropdown-toggle"
sort_by_price_low_loc = ".o_sortby_dropdown .dropdown-menu a[href*='order=list_price+asc']"
product_prices_loc = ".product_price .oe_currency_value"
