product_title_loc = "h1[itemprop='name']"
product_price_loc = ".oe_price .oe_currency_value"
product_image_loc = "img.product_detail_img"
add_to_cart_button_loc = "#add_to_cart"
success_message_loc = "xpath=//strong[contains(text(), 'Item(s) added to your cart')]"
cart_item_added_loc = "xpath=//*[contains(@class, 'my_cart_quantity')][contains(text(), '1')]"
quantity_input_loc = "input[name='add_qty']"
plus_button_loc = "a[title='Add one']"
minus_button_loc = "a[title='Remove one']"
